In [1]:
import jax

In [2]:
import numpy as np
import jax.numpy as jnp
from jax import random

In [6]:
dims = (15000, 15000)

def jax_raise_random_to_power(n):
    matrix = random.normal(random.PRNGKey(0), dims)
    jax.device_put(matrix)
    for i in range(n-1):
        matrix = jnp.dot(matrix, matrix)
    return matrix.block_until_ready()

def np_raise_random_to_power(n):
    matrix = random.normal(random.PRNGKey(0), dims)
    matrix = np.asarray(matrix)
    for i in range(n-1):
        matrix = np.dot(matrix, matrix)
    return matrix

In [8]:
%time jax_raise_random_to_power(5)

CPU times: user 6.62 ms, sys: 24 ms, total: 30.6 ms
Wall time: 2.22 s


Array([[-3.44836346e+31,  2.42456190e+31,  1.09931469e+31, ...,
        -4.74509574e+31,  1.87661349e+31,  2.80725970e+31],
       [-2.17017393e+31,  5.81911910e+30, -2.82345882e+31, ...,
         1.64935877e+31, -3.11280942e+31,  3.47848850e+30],
       [-3.17480990e+31, -2.01398978e+31,  9.12751506e+30, ...,
         1.26815388e+31,  6.97721503e+30, -6.60733269e+29],
       ...,
       [ 2.89065503e+31,  2.40937925e+31,  6.02446905e+30, ...,
         8.37971042e+30, -5.84394862e+30,  2.20225012e+31],
       [ 1.19755746e+30, -1.68081103e+31,  2.90124933e+31, ...,
         8.82043763e+29, -2.26268746e+31, -1.48451473e+31],
       [ 2.79858010e+31,  1.12208142e+31,  1.54133282e+30, ...,
         4.88697080e+30, -1.99746129e+30,  1.36222632e+31]],      dtype=float32)

In [9]:
%time np_raise_random_to_power(5)

CPU times: user 2min 25s, sys: 832 ms, total: 2min 26s
Wall time: 15.3 s


array([[-3.4483444e+31,  2.4245617e+31,  1.0992999e+31, ...,
        -4.7451069e+31,  1.8765957e+31,  2.8072452e+31],
       [-2.1701983e+31,  5.8190889e+30, -2.8234617e+31, ...,
         1.6493538e+31, -3.1128155e+31,  3.4782800e+30],
       [-3.1748026e+31, -2.0139880e+31,  9.1273144e+30, ...,
         1.2681501e+31,  6.9774193e+30, -6.6083656e+29],
       ...,
       [ 2.8906594e+31,  2.4093512e+31,  6.0245331e+30, ...,
         8.3796639e+30, -5.8439722e+30,  2.2022433e+31],
       [ 1.1975104e+30, -1.6808024e+31,  2.9012701e+31, ...,
         8.8187474e+29, -2.2627034e+31, -1.4845019e+31],
       [ 2.7985951e+31,  1.1220831e+31,  1.5414489e+30, ...,
         4.8871304e+30, -1.9973501e+30,  1.3621861e+31]], dtype=float32)

CPU times: user 3.73 ms, sys: 12.2 ms, total: 15.9 ms
Wall time: 12.9 ms


Array([[255.01978, 246.64871, 254.13368, ..., 233.67955, 247.6894 ,
        238.36868],
       [262.66006, 253.28917, 259.1826 , ..., 239.03181, 253.16742,
        249.44127],
       [259.38907, 252.72758, 258.23053, ..., 237.8357 , 252.41087,
        246.62466],
       ...,
       [256.15817, 250.09192, 254.72185, ..., 239.23868, 247.7267 ,
        244.16634],
       [268.2266 , 258.91202, 262.33414, ..., 245.26648, 259.05392,
        258.33707],
       [254.16147, 251.75418, 256.08313, ..., 238.59848, 245.62584,
        240.22353]], dtype=float32)

In [12]:
arr = jnp.asarray([[1.,2.,3.],[2.,3.,4.],[3.,4.,5.]])
jnp.average(arr, 0)

Array([2., 3., 4.], dtype=float32)

In [13]:
from random import sample
sample(list(range(100)), 10)

[97, 69, 36, 56, 70, 81, 57, 82, 75, 92]